### ISSUE TITLE
Artemis not detecting module

### ISSUE THREAD

**Issue by Kiks412** [diogotr7/Artemis.GSI.RocketLeague#1]
As title says im trying to use ur bakkes mod plugin but it i dont see anything happening

**Comment by diogotr7** [comment]
Did you import the plugin in Artemis? Does Rocket League show up on the Artemis side bar?

**Comment by Kiks412** [comment]
If u mean trying to import the plugin on the "seting-plugins" tab, then yes i downloaded the full zip and tryed to import but got an error.
unless is just a specific folder, then i dont know which one is it.
also no rocket league doesnt appear on the artemis program

**Comment by diogotr7** [comment]
Please post the full error. If you join the Artemis discord troubleshooting would be easier :p

**Comment by Kiks412** [comment]
okey i will try message you there.
